name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - id: test
      shell: pwsh
      run: env
    - id: tag
      shell: pwsh
      run: |
        if [ ${{github.ref_name}} == pull_request ]; then
          "::set-output name=tag::latest"
        else
          "::set-output name=tag::${{github.ref_name}}"
        fi
    - id: test1
      shell: pwsh
      run: echo "${{ steps.tag.outputs.tag }}"
#    - name: 'Login to GitHub Container Registry'
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{github.actor}}
#        password: ${{secrets.GITHUB_TOKEN}}
#    - id: lower-repo
#      shell: pwsh
#      run: |
#        "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
#    - uses: docker/build-push-action@v3
#      with:
#        push: true
#        tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{github.ref_name}}
        






