name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - id: lower-repo
      shell: pwsh
      run: |
        "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
        






